#!/bin/bash

apt-get update
apt-get install -y ipvsadm
apt-mark hold ipvsadm

f="/etc/modules"
for i in ip_vs_rr ip_vs_wrr ip_vs_sh ip_vs nf_conntrack_ipv4; do
  grep -q ^$i $f || echo $i >> $f;
  modprobe -- $i;
  lsmod | grep $i;
done

